---
title: "1. Rozkład empiryczny"
output: html_notebook
format: gfm
---
Rozkład empiryczny – sposób prezentacj:

Wczytaj zbiór przykład_oceny_w1 jako oceny
```{r}
library(readxl)
Komunikat ostrzegawczy:
oceny <- read_excel("przykład_oceny_w1.xlsx")
```

Liczebności absolutne: 
```{r}
library(dplyr)
tab1<-przykład_oceny_w1|>
  count(ocena_Xi)
```

Liczebności względne:  
```{r}
przykład_oceny_w1|>
  count(ocena_Xi)|>
  mutate(n_proc=n/sum(n))
```

Liczebności absolutne skumulowane: 
```{r}
przykład_oceny_w1|>
  count(ocena_Xi)|>
  mutate(n_proc=n/sum(n),cum=cumsum(n))
```

Skumulowane liczebności względne – DYSTRYBUANTA EMPIRYCZNA:
```{r}
przykład_oceny_w1|>
  count(ocena_Xi)|>
  mutate(n_proc=n/sum(n),cum=cumsum(n),cum_proc=cum/sum(n))
```

Wykres kolumnowy:
```{r}
library(ggplot2)
przykład_oceny_w1|>
  ggplot(aes(ocena_Xi))+
  geom_bar()
```
```{r}
table(Rossmann$czy_otwarty)
otwarte<-Rossmann|>
  filter(czy_otwarty=="Tak")
```
Histogram:
```{r}
otwarte|>
  ggplot(aes(sprzedaz))+
  geom_histogram()
```
szereg przedziałowy:
```{r}
library(dplyr)
tab2<-otwarte|>
  count(sprzedaz=cut(sprzedaz,c(-0.0001,1:20*2000),dig.lab = 5))
tab2
```

